### ISSUE TITLE
distinguish "text notes" from "commentary"

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#119]
We should label the textual notes in Marlowe and the Bellum Alexandrinum as "Text notes". Users see "commentary" as something different (although computationally, the two may be much the same!)

We will typically have textual notes and commentary.

**Comment by jacobwegner** [comment]
@gregorycrane Would you prefer "Text Notes" or "Critical Apparatus"?

I can customize the widget title dependent on the content...I wanted to use the "commentary" widget for scholia at some point too.  It is only called "Commentary" because we built it for a commentary display on another project and then brought it into Beyond Translation to demonstrate app crit.

**Comment by jacobwegner** [comment]
(Deploy pending in https://github.com/scaife-viewer/beyond-translation-site/pull/101)
