### ISSUE TITLE
Making credits more explicit

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#131]
We have worked on showing credits for treebanks, geospatial annotations, metrical analyses and other data but I can't see where/if we actually show people that Cynthia Damon edited the following or that it comes from the DLL. Am I missing something?

https://beyond-translation.perseus.org/reader/urn:cts:latinLit:phi0428.phi001.dll-preface-eng1:all?mode=fallback

**Comment by jacobwegner** [comment]
Hi @gregorycrane and @AlisonBabeu,

I would like to streamline our credits / attribution across Beyond Translation.

Alison is correct that we have the "Attributions" widget in use on scaife.perseus.org:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/629062/232065581-59862ddc-b7c1-4587-aa1a-5a63ebcb2995.png">

That data is extracted from the TEI headers, and we're not currently extracting the "editor" element:

https://github.com/PerseusDL/canonical-greekLit/blob/5f11cd7fb01236e04be11b915ac37fc4b3b3ebb5/data/tlg0012/tlg001/tlg0012.tlg001.perseus-grc2.xml#L7

Separately, we have the "Repository" widget:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/629062/232066644-f35ed3fd-5e50-42f4-832a-9a065fd1253a.png">

...which links back to the original repository.

The population for both of those widgets comes from the ingestion / extraction process we use on scaife.perseus.org.

For Beyond Translation, we use a different process.  The "Metadata" widget is showing information typically included in the `__cts__.xml` headers, but we're not actually using those headers at the moment, _or_ the source repositories.  Instead, we're loading "vendored" data stored directly in Beyond Translation:

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/629062/232067522-2c3b76d5-912d-4f9e-9f70-dc5b96a4b974.png">

Part of the work we'll be doing to "merge" functionality from Beyond Translation into scaife.perseus.org would help to standardize the display of the attributions / source repository data.

As @gregorycrane notes, we've done something different on Beyond Translation for annotation attribution; where possible, we're showing the attributions within the "widgets" or within the main reader when they are being viewed.  I've been toying with centralizing that information into the "Attributions" widget and making those results dynamic based on what annotations are being viewed...the underlying data model for attributions could support either a "centralized" or "distributed" approach, and I can see arguments for both.

We've also talked about having the ability to browse contributions from a particular person or organization, which the data model would also support.

So, back to the Balex...we are displaying the preface, which does mention Cynthia and the LDLT:

https://beyond-translation.perseus.org/reader/urn:cts:latinLit:phi0428.phi001.dll-preface-eng1:all?mode=fallback

<img width="891" alt="image" src="https://user-images.githubusercontent.com/629062/232069308-d3c26e21-c18d-4e8c-b04e-681e15e5a75e.png">

I'm using the metadata from https://catalog.perseus.org/catalog/urn:cts:latinLit:phi0428.phi001 (since the DLL doesn't have the `__cts__.xml` headers.

For the interim, if you would like me to add an "Editor" and "Repository" block to the metadata, I could do that:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/629062/232070548-b7ece4d4-eae8-4a51-9449-4d881221878e.png">

Would that work for now?

**Comment by AlisonBabeu** [comment]
hi @jacobwegner, you know I'm wondering if we should create cts_.xml files for any files that don't have them in the long run, so the system can have a consistent place to pull data from vs. the catalog fallback. Would there be a way for a  file ingest to trigger a request for a cts_.xml file to be created or for one to be created automatically. Sorry, just thinking out loud here. 

I like having the editor and repository show up in the meantime though, that helps add clarity!

**Comment by jacobwegner** [comment]
Let's discuss this on the call today.  I have a change ready to go for the Balex, and I can provide some additional context on any "fallbacks".

**Comment by jacobwegner** [comment]
@AlisonBabeu we discussed the "short-term" fix for Balex, but didn't get into any "long-term" discussions on the headers.

I'm happy to elaborate on this more in the future, but the TLDR is that:
- For "Scaife", we're only loading texts with Capitans metadata
- For "Beyond Translation", we're a bit looser on metadata; I just searched for the URNs and metadata within catalog.perseus.org and copied into a JSON / YAML file

I think we can continue to support both; it sounds like the work that Greg wants Charles to do this summer could benefit from some kind of a tool that makes use of the catalog data to create the CTS headers.
