### ISSUE TITLE
rendering issue with wide trees

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#188]
https://beyond-translation-dev.perseus.org/reader/urn:cts:greekLit:tlg0003.tlg001.perseus-grc2:1.1.1-1.1.3?collectionUrn=urn%3Acite2%3Abeyond-translation%3Atext_annotation_collection.atlas_v1%3Aglaux_trees&mode=syntax-trees

The tree is truncated on the right side.

![image](https://github.com/scaife-viewer/beyond-translation-site/assets/5159577/8dc7910f-3c53-49ac-a792-18494d355f72)

**Comment by jacobwegner** [comment]
@gregorycrane I'll take a look.  There is some interplay between the width of the "viewport" on the browser and the rendered tree that I suspect is at issue.

**Comment by jacobwegner** [comment]
@gregorycrane I'm working on a new deployment that will fix this bug in production.  The fix won't be on `beyond-translation-dev` yet, but I'll work around to it as part of doing additional data updates.

I'll ping you on this thread when the fix is live.

**Comment by jacobwegner** [comment]
Fixed in https://github.com/scaife-viewer/beyond-translation-site/releases/tag/v2023-12-22-001

https://beyond-translation.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1-1.7?mode=syntax-trees&collectionUrn=urn%3Acite2%3Abeyond-translation%3Atext_annotation_collection.atlas_v1%3Aglaux_trees
