### ISSUE TITLE
data question: why does klisih not appear as a vocab word in Il. 1.185?

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#57]
https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.182-1.192?mode=alignments&rs=urn%3Acite2%3Ascaife-viewer%3Aalignment.v1%3Ailiad-word-alignment-parrish-998078bc3bab42978b47fa8e8b852cae

Are we still using Giuseppe's lemmatization here? NB: some editions combine klisihn + de and present this as one word, rather than two.

![image](https://user-images.githubusercontent.com/5159577/160282248-7660609d-f772-44d0-a656-b617ed528c2d.png)

![image](https://user-images.githubusercontent.com/5159577/160282266-69beb0cb-4d31-4cb4-a9e2-24e2f8c0ffff.png)

![image](https://user-images.githubusercontent.com/5159577/160282279-40ea856a-781e-4d74-abd2-635dd6c8e3b9.png)

**Comment by jacobwegner** [comment]
@gregorycrane When the user makes a selection, we do a lookup for the lemma against Morpheus (in the _Morphology_ widget):

![image](https://user-images.githubusercontent.com/629062/160298494-c4b165ed-633c-462d-b148-a9524625067c.png)

Morpheus is returning `κλισι-ην`, so that is what we end up using to query the dictionaries.

I've got a few other query-by-lemma tweaks I'm working on this week; let's touch base on Tuesday to see if any of them help  this edge case.

**Comment by jacobwegner** [comment]
I've switched Cunliffe over to using the `n` attributes for headwords; I've also created #61  to help deal with the "fallback" issue (where Morpheus differs from our "curated" lemmas)

**Comment by jacobwegner** [comment]
[View on the preview instance:](https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.185?entryUrn=urn%3Acite2%3AexploreHomer%3Aentries.atlas_v1%3A1.5625)

![image](https://user-images.githubusercontent.com/629062/161751175-17ab09ba-bbe4-4245-a1f6-b3746d1432f3.png)
